{
 "title": "Bazel Farm 编译集群监控大屏",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "db", "label": "DB", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": { "query": "label_values(job)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values({job=~\"$job\"},instance)"
    }
   },
   {
    "name": "myInterval",
    "label": "Interval",
    "query": "1m,2m, 5m, 10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "worker_pool_size",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "worker_pool_size", "legendFormat": "{{job}} / {{instance}} " }
   ]
  },
  {
   "title": "health_check",
   "type": "timeseries",
   "description": "Counter showing service restarts",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "health_check_total", "legendFormat": "{{job}} / {{instance}}" }
   ]
  },
  { "title": "Cas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "remote_invocations",
   "type": "timeseries",
   "description": "Counter for the number of invocations of the capabilities service",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "remote_invocations_created{instance=~\"$instance\"}",
     "legendFormat": "{{job}} / {{instance}} created"
    },
    {
     "expr": "remote_invocations_total{instance=~\"$instance\"}",
     "legendFormat": "{{job}} / {{instance}} total"
    }
   ]
  },
  {
   "title": "expired_key",
   "type": "timeseries",
   "description": "Counter for key expirations",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "expired_key_total", "legendFormat": "{{job}} / {{instance}} total" },
    {
     "expr": "rate(expired_key_created[$myInterval])",
     "legendFormat": "{{job}} / {{instance}} created"
    }
   ]
  },
  {
   "title": "execution_success",
   "type": "timeseries",
   "description": "Counter for the number of successful executions",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "execution_success_total", "legendFormat": "{{job}} / {{instance}} total" }
   ]
  },
  {
   "title": "pre_queue_size",
   "type": "timeseries",
   "description": "Gauge of a number of items in prequeue",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "pre_queue_size", "legendFormat": "{{job}} / {{instance}}" }
   ]
  },
  {
   "title": "queue_size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "expr": "queue_size", "legendFormat": "{{job}} / {{instance}}" }
   ]
  },
  {
   "title": "requeue_failure",
   "type": "timeseries",
   "description": "Counter for number of operations that failed to requeue",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "requeue_failure_created", "legendFormat": "{{job}} / {{instance}} created" },
    { "expr": "requeue_failure_total", "legendFormat": "{{job}} / {{instance}} total" },
    {
     "expr": "rate(requeue_failure_created[$myInterval])",
     "legendFormat": "{{job}} / {{instance}} created rate"
    },
    {
     "expr": "rate(requeue_failure_total[$myInterval])",
     "legendFormat": "{{job}} / {{instance}} total rate"
    }
   ]
  },
  {
   "title": "queue_failure",
   "type": "timeseries",
   "description": "Counter for number of CAS misses from worker-worker",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "queue_failure_total", "legendFormat": "{{job}} / {{instance}} total" },
    {
     "expr": "rate(queue_failure_created[$myInterval])",
     "legendFormat": "{{job}} / {{instance}} created"
    }
   ]
  },
  {
   "title": "cas_size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cas_size{instance=~\"$instance\"}",
     "legendFormat": "{{job}} / {{instance}}"
    }
   ]
  },
  {
   "title": "cas_miss",
   "type": "timeseries",
   "description": "Counter for number of CAS misses from worker-worker",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "rate(cas_miss_created[$myInterval])",
     "legendFormat": "{{job}} / {{instance}} created"
    },
    {
     "expr": "rate(cas_miss_total[$myInterval])",
     "legendFormat": "{{job}} / {{instance}} total"
    }
   ]
  },
  {
   "title": "cas_entry_count",
   "type": "timeseries",
   "description": "Counter for number of CAS misses from worker-worker",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "rate(cas_entry_count[$myInterval])",
     "legendFormat": "{{job}} / {{instance}} "
    }
   ]
  },
  { "title": "Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "dispatched_operations_size",
   "type": "timeseries",
   "description": "Gauge of the number of dispatched operations",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
   "targets": [
    { "expr": "dispatched_operations_size", "legendFormat": "{{job}} / {{instance}}" }
   ]
  },
  {
   "title": "actions & action_results",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "actions_created", "legendFormat": "{{job}} / {{instance}} created" },
    { "expr": "actions_total", "legendFormat": "{{job}} / {{instance}} total" },
    {
     "expr": "action_results_created",
     "legendFormat": "{{job}} / {{instance}} result created"
    },
    {
     "expr": "action_results_total",
     "legendFormat": "{{job}} / {{instance}} result total"
    }
   ]
  },
  {
   "title": "missing_blobs",
   "type": "timeseries",
   "description": "Histogram for the number of missing blobs",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "rate(missing_blobs_count[5m])", "legendFormat": "{{job}} / {{instance}} count" }
   ]
  },
  {
   "title": "execution_time_ms",
   "type": "timeseries",
   "description": "Histogram for the execution time on a worker (in milliseconds)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(execution_time_ms_sum[5m])",
     "legendFormat": "{{job}} / {{instance}} sum"
    },
    {
     "expr": "rate(execution_time_ms_count[5m])",
     "legendFormat": "{{job}} / {{instance}} count"
    },
    { "expr": "execution_time_ms_created", "legendFormat": "{{job}} / {{instance}} create" }
   ]
  },
  {
   "title": "execution_stall_time_ms",
   "type": "timeseries",
   "description": "Histogram for the execution stall time on a worker (in milliseconds)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(execution_stall_time_ms_sum[5m])",
     "legendFormat": "{{job}} / {{instance}} sum"
    },
    {
     "expr": "rate(execution_stall_time_ms_count[5m])",
     "legendFormat": "{{job}} / {{instance}} count"
    },
    {
     "expr": "execution_stall_time_ms_created",
     "legendFormat": "{{job}} / {{instance}} create"
    }
   ]
  },
  {
   "title": "execution_slot",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 75 },
   "targets": [
    { "expr": "execution_slot_usage", "legendFormat": "{{job}} / {{instance}} usage" },
    { "expr": "execution_slots_total", "legendFormat": "{{job}} / {{instance}} total" }
   ]
  },
  {
   "title": "input_fetch_slot_usage",
   "type": "timeseries",
   "description": "Gauge for the number of input fetch slots used on each worker",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 75 },
   "targets": [
    { "expr": "input_fetch_slot_usage", "legendFormat": "{{job}} / {{instance}} sum" }
   ]
  },
  {
   "title": "input_fetch_time_ms",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(input_fetch_time_ms_sum[5m])",
     "legendFormat": "{{job}} / {{instance}} sum"
    },
    {
     "expr": "rate(input_fetch_time_ms_count[5m])",
     "legendFormat": "{{job}} / {{instance}} count"
    },
    { "expr": "input_fetch_time_ms_created", "legendFormat": "{{job}} / {{instance}} create" }
   ]
  },
  {
   "title": "input_fetch_stall_time_ms",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(input_fetch_stall_time_ms_sum[5m])",
     "legendFormat": "{{job}} / {{instance}} sum"
    },
    {
     "expr": "rate(input_fetch_stall_time_ms_count[5m])",
     "legendFormat": "{{job}} / {{instance}} count"
    },
    {
     "expr": "input_fetch_stall_time_ms_created",
     "legendFormat": "{{job}} / {{instance}} create"
    }
   ]
  },
  {
   "title": "queued_time_ms",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "rate(queued_time_ms_sum[5m])", "legendFormat": "{{job}} / {{instance}} sum" },
    { "expr": "rate(queued_time_ms_count[5m])", "legendFormat": "{{job}} / {{instance}} count" },
    { "expr": "queued_time_ms_created", "legendFormat": "{{job}} / {{instance}} create" }
   ]
  },
  {
   "title": "output_upload_time_ms",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(output_upload_time_ms_sum[5m])",
     "legendFormat": "{{job}} / {{instance}} sum"
    },
    {
     "expr": "rate(output_upload_time_ms_count[5m])",
     "legendFormat": "{{job}} / {{instance}} count"
    },
    { "expr": "output_upload_time_ms_created", "legendFormat": "{{job}} / {{instance}} create" }
   ]
  },
  {
   "title": "completed_operations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "completed_operations_total", "legendFormat": "{{job}} / {{instance}} total" }
   ]
  },
  {
   "title": "operation_poller",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(operation_poller_created[$myInterval])",
     "legendFormat": "{{job}} / {{instance}} rate create"
    },
    {
     "expr": "rate(operation_poller_total[$myInterval])",
     "legendFormat": "{{job}} / {{instance}} rate total"
    }
   ]
  },
  {
   "title": "io_bytes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(io_bytes_read_sum[5m])",
     "legendFormat": "read: {{job}} / {{instance}} sum"
    },
    {
     "expr": "rate(io_bytes_read_count[5m])",
     "legendFormat": "read: {{job}} / {{instance}} count"
    },
    {
     "expr": "rate(io_bytes_read_created[5m])",
     "legendFormat": "read: {{job}} / {{instance}} create"
    },
    {
     "expr": "rate(io_bytes_write_sum[5m])",
     "legendFormat": "write: {{job}} / {{instance}} sum"
    },
    {
     "expr": "rate(io_bytes_write_count[5m])",
     "legendFormat": "write: {{job}} / {{instance}} count"
    },
    {
     "expr": "rate(io_bytes_write_created[5m])",
     "legendFormat": "write: {{job}} / {{instance}} create"
    }
   ]
  },
  { "title": "Jvm", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 114 } },
  {
   "title": "JVM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{instance=~\"$instance\"}",
     "legendFormat": "{{job}} / {{instance}} {{area}}"
    }
   ]
  }
 ]
}